### ISSUE TITLE
Dataset can't be downloaded

### ISSUE THREAD

**Issue by luxius-luminus** [matheusgadelha/MRTNet#1]
Thanks for your contribution!
Yet I encountered a problem here:)
The URL of dataset is given by "http://bluenoise.cs.umass.edu:8000/shapenet_points.zip".
But neither the Chrome browser nor wget can access the URL above.

**Comment by luxius-luminus** [comment]
UPDATE:
when I use wget to retrieve the given URL, it says
`Connecting to bluenoise.cs.umass.edu (bluenoise.cs.umass.edu)|128.119.243.14|:8000... failed: Connection refused.`
so it might be the server's issue...(It can't be that my IP is blocked....)

**Comment by matheusgadelha** [comment]
There is an issue with the server, as soon as I sort it out I will let you know.

**Comment by matheusgadelha** [comment]
I added code to sample the points from meshes if it helps, while the server is not fixed. It is in the `sampler` folder.
