### ISSUE TITLE
DataVis can't be found 

### ISSUE THREAD

**Issue by Estellepark** [matheusgadelha/MRTNet#2]
Excuse me, during the training process: Python train_img2pc.py -- name experiment_name; the following errors occurred: File: tools/Trainer.py, line 6, import error: No module named DataVis. Is DataVis a library of pytorch? I can't find it anyway. Please answer it.Thanks very much

**Comment by matheusgadelha** [comment]
Those are just for visualization using visdom. You can just remove any lines that are importing/using DataVis. In any case, I added the script to repository. If you have visdom installed, just run the updated code. Hope it helped.
