### ISSUE TITLE
About the cotSpectral.java

### ISSUE THREAD

**Issue by 2018whr** [matheusgadelha/MRTNet#5]
Hello,first,thanks for your contributions!
when i try to use the cotSpectral.java,some exception happened
I use a tennisball.obj to do a experiment,and the command is 'java -cp .:./vecmath.jar cotSpectral tennisball.obj out.obj 1024'
And the exception is 
tennisball.obj radius = 10.273081
number of samples: 1024 (rho=0.75)
Exception in thread "main" java.lang.NullPointerException
	at cotSpectral.saveSamples(cotSpectral.java:204)
	at cotSpectral.main(cotSpectral.java:193)
I can't figure out this,please help me.
Thanks again!

**Comment by buttomnutstoast** [comment]
You just need to comment out `f.getParentFile().mkdirs();` at L204 in cotSpectral.java, and then recompile.
