### ISSUE TITLE
How to get the point cloud data

### ISSUE THREAD

**Issue by peterjohnsonhuang** [matheusgadelha/MRTNet#6]
First, thanks for the contribution. I am a beginner of point cloud dataset, so I had trouble about how to get them, since the readme.md only mentioned about the rendered image. Thank you.

**Comment by matheusgadelha** [comment]
You can sample points from any mesh using the program in the ``sampler`` folder. Then, given a dataset with meshes (like ShapeNet) you can generate your own point cloud dataset.
