### ISSUE TITLE
how to visualize .obj file saved

### ISSUE THREAD

**Issue by peterjohnsonhuang** [matheusgadelha/MRTNet#7]
Hello, 
I'm sorry to have another problem about visualizing the .obj file saved after training or testing. I tried to use https://3dviewer.net/ this site to visualize them but failed. So may I ask how to visualize them? Thank you.

**Comment by matheusgadelha** [comment]
The point clouds are saved as vertices of a mesh. It is kind of a hack, but it is easier to visualize in more popular 3D software. Meshlab or blender work perfectly, for example. I think meshlab is more suitable, blender might be an overkill.
